import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "en" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.training": "DevWady Academy",
    "nav.blog": "Blog",
    "nav.team": "Our Team",
    "nav.gallery": "Gallery",
    "nav.media": "Media",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact Us",
    "nav.consulting": "Consulting",
    "nav.hiring": "Hiring & Freelancers",
    "nav.more": "More",
    "nav.getStarted": "Get Started",
    "nav.myProfile": "My Profile",
    "nav.editProfile": "Edit Profile",
    "nav.myBookings": "My Bookings",
    "nav.adminPanel": "Admin Panel",
    "nav.signOut": "Sign Out",

    // Hero
    "hero.tagline": "Technology & Software Company",
    "hero.title1": "Real-World Experience,",
    "hero.title2": "Delivered to You.",
    "hero.subtitle": "We design, develop, and scale end-to-end digital ecosystems that ship real value. Mobile Apps, Websites, Enterprise Systems, and more.",
    "hero.cta1": "Start Your Project",
    "hero.cta2": "Explore Services",
    "hero.stat1": "25+",
    "hero.stat1Label": "Expert Professionals",
    "hero.stat2": "Egypt & KSA",
    "hero.stat2Label": "Operating Regions",
    "hero.stat3": "3",
    "hero.stat3Label": "Business Sectors",

    // About
    "about.title": "Who We Are",
    "about.subtitle": "DevWady is a product-first technology & software company based in Cairo, Egypt, operating across Egypt and KSA.",
    "about.description": "With 25+ professionals, we design, develop, and scale end-to-end digital ecosystems that ship real value. We started as a builder ecosystem — not a typical software company. Our journey began with a different training model: not 'learning to code', but learning by shipping.",
    "about.vision": "Vision",
    "about.visionText": "To become the most trusted product-minded delivery partner in Egypt and KSA — building scalable digital ecosystems and producing market-ready tech talent.",
    "about.mission": "Mission",
    "about.missionText": "We deliver real-world software products end-to-end, provide high-performing teams through outsourcing, and accelerate companies and talent through consulting and advanced training.",
    "about.promise": "We Build. We Ship. We Scale.",
    "about.value1": "Ship Real Value",
    "about.value1Desc": "Outcomes matter more than output",
    "about.value2": "Quality by Design",
    "about.value2Desc": "QA is part of building, not a final step",
    "about.value3": "Product Mindset",
    "about.value3Desc": "Understand the market before writing code",
    "about.value4": "Transparency",
    "about.value4Desc": "Clear plans, progress, risks, and accountability",
    "about.value5": "Growth Culture",
    "about.value5Desc": "Mentorship, learning, and continuous improvement",

    // Services
    "services.title": "What We Do",
    "services.subtitle": "End-to-end technology solutions across three connected sectors",
    "services.delivery": "Software Delivery",
    "services.deliveryDesc": "End-to-end products from concept to launch with quality embedded at every step.",
    "services.outsourcing": "Outsourcing & Staffing",
    "services.outsourcingDesc": "Scale your team with elite technical talent through flexible engagement models.",
    "services.consulting": "Consulting & Training",
    "services.consultingDesc": "Future-proof your technology infrastructure and empower your people.",
    "services.mobileApps": "Mobile Apps",
    "services.mobileAppsDesc": "High-performance iOS & Android applications — multi-user ecosystems.",
    "services.websites": "Websites & CMS",
    "services.websitesDesc": "Corporate portals, custom CMS platforms, and scalable web applications.",
    "services.enterprise": "Enterprise Systems",
    "services.enterpriseDesc": "School management, Logistics/ERP, Restaurant POS — robust platforms.",
    "services.uiux": "UI/UX Design",
    "services.uiuxDesc": "User journeys, wireframing, prototyping, and design systems.",
    "services.qa": "Software QA",
    "services.qaDesc": "Integrated testing, regression, and performance audits.",
    "services.itServices": "IT Services",
    "services.itServicesDesc": "Infrastructure, cloud setup, DevOps, and technical support.",

    // Portfolio
    "portfolio.title": "Our Products & Projects",
    "portfolio.subtitle": "Selected products delivered across transportation, logistics, real estate, education, and enterprise.",
    "portfolio.yozya": "YOZYA Ecosystem",
    "portfolio.yozyaDesc": "A connected multi-module platform — Real Estate, Services Marketplace, Transportation. Master App + Website + Partner Platform + CMS.",
    "portfolio.atmodrive": "AtmoDrive",
    "portfolio.atmodriveDesc": "Complete ride-hailing transportation system — Passenger App, Captain App, CMS with live tracking, payments, analytics.",
    "portfolio.hamla": "HAMLA",
    "portfolio.hamlaDesc": "Goods logistics platform — Client App, Captain App, Provider Portal, CMS with multi-stop routing & live tracking.",
    "portfolio.majesty": "Majesty International Schools",
    "portfolio.majestyDesc": "Integrated school management system — Parent App, CMS for grades, behavior, fees, bus tracking.",
    "portfolio.nuut": "nuut.ai & nuut POS",
    "portfolio.nuutDesc": "AI-powered restaurant POS system — Customer App, Waiter App, Kitchen Display, full CMS.",
    "portfolio.flagship": "Flagship",
    "portfolio.visitWebsite": "Visit Website",
    "portfolio.androidApp": "Android App",
    "portfolio.iosApp": "iOS App",
    "portfolio.alliance": "Alliance Engineering",
    "portfolio.allianceDesc": "Corporate website for Alliance Arabia engineering services — responsive design, brand identity, and service showcase.",
    "portfolio.maamour": "Ma'amour Arabia",
    "portfolio.maamourDesc": "Premium corporate presence for Ma'amour Arabia — elegant design, multi-section landing page.",
    "portfolio.rissad": "Rissad",
    "portfolio.rissadDesc": "Digital platform built on modern web technologies — clean UI, responsive layouts, and seamless user experience.",

    // Training
    "training.title": "DevWady Academy",
    "training.subtitle": "Learn by Shipping Real Products",
    "training.description": "Applied bootcamps & corporate training that produce delivery-ready professionals — not just certificate holders.",
    "training.methodology": "The \"Learning-by-Shipping\" Method",
    "training.methodDesc": "Unlike traditional training that ends with a certificate, our bootcamps immerse you in real product delivery cycles.",
    "training.step1": "Learn",
    "training.step1Desc": "Core concepts, frameworks & best practices",
    "training.step2": "Build",
    "training.step2Desc": "Hands-on project work on real product features",
    "training.step3": "Ship",
    "training.step3Desc": "Deploy to production with CI/CD & quality gates",
    "training.step4": "Iterate",
    "training.step4Desc": "Code reviews, feedback loops & refinement",
    "training.android": "Native Android Development",
    "training.androidDesc": "Kotlin — Build production-ready Android apps (Advanced)",
    "training.ios": "Native iOS Development",
    "training.iosDesc": "Swift — Build production-ready iOS apps (Advanced)",
    "training.flutter": "Flutter Cross-Platform",
    "training.flutterDesc": "Dart — Build apps for iOS, Android & Web from one codebase",
    "training.frontend": "Frontend Development",
    "training.frontendDesc": "React & JavaScript — Build modern interactive web applications",
    "training.backend": "Backend Development",
    "training.backendDesc": "PHP & Laravel — Design scalable server architectures (Advanced)",
    "training.sdet": "SDET Bootcamp",
    "training.sdetDesc": "Testing automation — Master automated testing & quality engineering",
    "training.design": "UI/UX Design",
    "training.designDesc": "Figma + Systems — Create production-ready design systems",
    "training.devops": "DevOps & Cloud",
    "training.devopsDesc": "AWS, Docker & Kubernetes — Build and deploy cloud infrastructure",
    "training.aiml": "AI & Machine Learning",
    "training.aimlDesc": "Python, TensorFlow & PyTorch — Build intelligent applications",
    "training.cybersecurity": "Cybersecurity Fundamentals",
    "training.cybersecurityDesc": "Ethical hacking, penetration testing & security audits",
    "training.product": "Product Management",
    "training.productDesc": "Strategy + Agile — Lead products from vision to delivery",
    "training.corporate": "Corporate Custom",
    "training.corporateDesc": "Tailored programs for your team",
    "training.enrollNow": "Enroll Now",
    "training.viewCourses": "View All Courses",
    "training.weeks": "Weeks",
    "training.flexible": "Flexible",
    "training.whoFor": "Who Is This For?",
    "training.freshGrads": "Fresh Graduates",
    "training.juniorDevs": "Junior Developers",
    "training.careerSwitchers": "Career Switchers",
    "training.corporateTeams": "Corporate Teams",
    "training.freelancers": "Freelancers",

    // Team
    "team.title": "Meet Our Team",
    "team.subtitle": "The talented professionals behind DevWady's success",
    "team.leadership": "Leadership",
    "team.developers": "Development Team",
    "team.trainees": "From Trainee to Team Member",
    "team.traineesDesc": "These professionals started in our Training Academy and now are full-time DevWady team members — proof that our learning-by-shipping model works.",
    "team.joinUs": "Join Our Team",
    "team.joinUsDesc": "We're always looking for talented individuals who share our passion for building great products.",
    "team.applyNow": "Apply Now",

    // Blog
    "blog.title": "Blog & Insights",
    "blog.subtitle": "Thoughts on technology, product development, and building great teams",
    "blog.readMore": "Read More",
    "blog.minRead": "min read",
    "blog.latest": "Latest Articles",
    "blog.categories": "Categories",
    "blog.all": "All",
    "blog.tech": "Technology",
    "blog.product": "Product",
    "blog.culture": "Culture",
    "blog.training": "Academy",

    // Gallery
    "gallery.title": "Gallery & Story",
    "gallery.subtitle": "Our journey from day one to where we are today",
    "gallery.timeline": "Our Timeline",
    "gallery.photos": "Life at DevWady",
    "gallery.events": "Events & Milestones",

    // Media / Online Activities
    "media.title": "Online Activities",
    "media.subtitle": "Videos, reels, podcasts, and content about tech, work culture, and business insights",
    "media.videos": "Videos & Reels",
    "media.podcasts": "Podcasts",
    "media.techTalks": "Tech Talks",
    "media.workLife": "Work & Life",
    "media.business": "Market & Business",
    "media.watchNow": "Watch Now",
    "media.listenNow": "Listen Now",

    // Pricing
    "pricing.title": "Pricing & Packages",
    "pricing.subtitle": "Transparent · Flexible · Scalable",
    "pricing.projectBased": "Project-Based Delivery",
    "pricing.projectBasedDesc": "Discovery, UI/UX Design, Development, QA, Deployment & Launch Support",
    "pricing.projectBasedFor": "Best for: New Launches",
    "pricing.dedicatedSquads": "Dedicated Squads",
    "pricing.dedicatedSquadsDesc": "Full-Stack Devs, UI/UX & QA Specialists, Continuous Agile Governance",
    "pricing.dedicatedSquadsFor": "Best for: Scaling Products",
    "pricing.teamAug": "Team Augmentation",
    "pricing.teamAugDesc": "Elite-level senior talent on demand, seamless integration into your workflow",
    "pricing.teamAugFor": "Best for: Filling Skill Gaps",
    "pricing.consulting": "Consulting Retainer",
    "pricing.consultingDesc": "Architecture & Security Audits, Product Roadmap & Maturity Planning",
    "pricing.consultingFor": "Best for: Leadership & Strategy",
    "pricing.contactQuote": "Contact for Quote",
    "pricing.requestQuote": "Request Quote",
    "pricing.popular": "Most Popular",

    // Contact
    "contact.title": "Let's Build Something Great",
    "contact.subtitle": "Get a detailed quote for your project within 48 hours.",
    "contact.name": "Your Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.message": "Tell us about your project",
    "contact.send": "Send Message",
    "contact.or": "Or reach us directly",

    // Footer
    "footer.tagline": "Real-World Experience, Delivered to You",
    "footer.rights": "© 2026 DevWady. All rights reserved.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.contactInfo": "Contact Info",
    "footer.followUs": "Follow Us",

    // Profile
    "profile.myBookings": "My Bookings",
    "profile.bookingsSubtitle": "Track your consulting sessions",
    "profile.backToProfile": "← My Profile",

    // SEO
    "seo.home.title": "DevWady — Technology & Software Company",
    "seo.home.desc": "We design, develop, and scale end-to-end digital ecosystems across Egypt & KSA.",
    "seo.about.title": "About Us",
    "seo.about.desc": "DevWady is a product-first technology company based in Cairo with 25+ professionals.",
    "seo.services.title": "Our Services",
    "seo.services.desc": "Mobile Apps, Websites, Enterprise Systems, UI/UX Design, QA, and IT Services.",
    "seo.portfolio.title": "Our Portfolio",
    "seo.portfolio.desc": "Real products we've built — YOZYA, AtmoDrive, HAMLA, and more.",
    "seo.training.title": "DevWady Academy",
    "seo.training.desc": "Hands-on training tracks led by industry professionals.",
    "seo.blog.title": "Blog",
    "seo.blog.desc": "Technical insights, product stories, and company culture from the DevWady team.",
    "seo.team.title": "Our Team",
    "seo.team.desc": "Meet the professionals behind DevWady.",
    "seo.consulting.title": "Expert Consulting",
    "seo.consulting.desc": "Book 1-on-1 sessions with senior tech experts.",
    "seo.hiring.title": "Hiring & Freelancers",
    "seo.hiring.desc": "Find top tech talent or browse open positions.",
    "seo.pricing.title": "Pricing",
    "seo.pricing.desc": "Flexible engagement models for projects of any size.",
    "seo.contact.title": "Contact Us",
    "seo.contact.desc": "Get in touch for a free consultation.",
    "seo.gallery.title": "Gallery",
    "seo.gallery.desc": "Our journey and milestones.",
    "seo.media.title": "Media",
    "seo.media.desc": "Videos, podcasts, and appearances.",
    "seo.login.title": "Sign In",
    "seo.signup.title": "Create Account",
    "seo.forgotPassword.title": "Forgot Password",
    "seo.resetPassword.title": "Reset Password",
    "seo.notFound.title": "Page Not Found",
    "seo.profile.title": "My Profile",
    "seo.profileEdit.title": "Edit Profile",
    "seo.profileBookings.title": "My Bookings",
    "seo.profileApplications.title": "My Applications",
    "seo.consultingRequest.title": "Book a Consultation",
    "seo.consultingTrack.title": "Track Booking",
    "seo.onboarding.title": "Get Started",
    "seo.companyDashboard.title": "Company Dashboard",
    "seo.companyProfile.title": "Company Profile",
    "seo.companyJobs.title": "My Job Postings",
    "seo.companyShortlists.title": "Shortlisted Talent",
    "seo.companyTalent.title": "Browse Talent",

    // Admin
    "admin.console": "Admin Console",
    "admin.dashboard": "Dashboard",
    "admin.blogPosts": "Blog Posts",
    "admin.portfolio": "Portfolio",
    "admin.services": "Services",
    "admin.teamMembers": "Team Members",
    "admin.testimonials": "Testimonials",
    "admin.training": "Academy",
    "admin.hiring": "Hiring",
    "admin.engagements": "Engagements",
    "admin.experts": "Experts",
    "admin.bookings": "Bookings",
    "admin.contacts": "Contact Inbox",
    "admin.serviceRequests": "Service Requests",
    "admin.quotes": "Quotes",
    "admin.projectTracking": "Projects",
    "admin.media": "Media Library",
    "admin.gallery": "Gallery",
    "admin.users": "Users",
    "admin.content": "Content",
    "admin.operations": "Operations",
    "admin.backToSite": "Back to Site",
    "admin.signOut": "Sign Out",
    "admin.create": "Create",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.search": "Search",
    "admin.filter": "Filter",
    "admin.noData": "No data found",
    "admin.overview": "Overview",
    "admin.submissions": "Submissions",
    "admin.refresh": "Refresh",
    "admin.actions": "Actions",
    "admin.status": "Status",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.loading": "Loading…",
    "admin.welcomeBack": "Welcome Back",
    "admin.commandCenter": "Command Center",
    "admin.liveNow": "live now",
    "admin.liveVisitors": "Live Visitors",
    "admin.viewsToday": "Views Today",
    "admin.uniqueVisitors": "Unique Visitors",
    "admin.views7d": "Views (7d)",
    "admin.trafficOverview": "Traffic Overview",
    "admin.last7days": "Last 7 days",
    "admin.topPages": "Top Pages",
    "admin.noPageViews": "No page views yet",
    "admin.recentBookings": "Recent Bookings",
    "admin.noBookings": "No bookings yet",
    "admin.recentMessages": "Recent Messages",
    "admin.noMessages": "No messages yet",
    "admin.months6": "6 months",
    "admin.dateRange": "Date range",
    "admin.last7Days": "Last 7 days",
    "admin.last30Days": "Last 30 days",
    "admin.last3Months": "Last 3 months",
    "admin.last6Months": "Last 6 months",
    "admin.thisYear": "This year",
    "admin.allTime": "All time",
    "admin.platformOverview": "Platform Overview",
    "admin.exportCSV": "Export CSV",
    "admin.downloadReport": "Download Report",
    "admin.notificationCenter": "Notification Center",
    "admin.sendBroadcast": "Send Broadcast",
    "admin.targetAudience": "Target Audience",
    "admin.allUsers": "All Users",
    "admin.allIndividuals": "All Individuals",
    "admin.allCompanies": "All Companies",
    "admin.allAdmins": "All Admins",
    "admin.totalNotifications": "Total Sent",
    "admin.unreadNotifications": "Unread",
    "admin.notificationsToday": "Today",
    "admin.mostActiveType": "Most Active Type",
    "admin.notificationsSent": "Notifications Sent",
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all read",
    "notifications.empty": "No notifications yet",
    "notifications.viewAll": "View all notifications",
    "notifications.tabAll": "All",
    "notifications.tabUnread": "Unread",
    "notifications.tabBookings": "Bookings",
    "notifications.tabJobs": "Jobs",
    "notifications.tabSystem": "System",
    "notifications.noNotifications": "No notifications",
    "notifications.allCaughtUp": "You're all caught up!",
    "notifications.viewDetails": "View details",
    "notifications.loadMore": "Load more",
    "notifications.markRead": "Mark as read",
    "admin.quickAccess": "Quick Access",
    "admin.viewAll": "View all",
    "admin.projects": "Projects",
    "admin.team": "Team",
    "admin.messages": "Messages",
    "admin.administrator": "Administrator",
    "admin.searchPlaceholder": "Search...",
    "admin.manageContent": "Manage your blog content",
    "admin.newPost": "New Post",
    "admin.noPostsYet": "No blog posts yet",
    "admin.title": "Title",
    "admin.category": "Category",
    "admin.date": "Date",
    "admin.managePortfolio": "Manage portfolio entries",
    "admin.newProject": "New Project",
    "admin.noProjectsYet": "No projects yet",
    "admin.featured": "Featured",
    "admin.manageTeam": "Manage your team",
    "admin.addMember": "Add Member",
    "admin.noMembersYet": "No team members yet",
    "admin.name": "Name",
    "admin.role": "Role",
    "admin.department": "Department",
    "admin.manageContacts": "Manage messages from the contact form",
    "admin.searchContacts": "Search by name, email, or subject…",
    "admin.selected": "selected",
    "admin.markRead": "Mark Read",
    "admin.markReplied": "Mark Replied",
    "admin.archive": "Archive",
    "admin.from": "From",
    "admin.subject": "Subject",
    "admin.noMessagesFound": "No messages found",
    "admin.messageFrom": "Message from",
    "admin.email": "Email",
    "admin.phone": "Phone",
    "admin.message": "Message",
    "admin.updateStatus": "Update Status",
    "admin.adminNotes": "Admin Notes",
    "admin.addNotes": "Add internal notes about this submission…",
    "admin.saveNotes": "Save Notes",
    "admin.saving": "Saving…",
    "admin.received": "Received",
    "admin.manageBookings": "Manage consulting session bookings and new requests",
    "admin.bookingsRequests": "Bookings & Requests",
    "admin.total": "Total",
    "admin.newRequests": "New Requests",
    "admin.confirmed": "Confirmed",
    "admin.completed": "Completed",
    "admin.cancelled": "Cancelled",
    "admin.requests": "Requests",
    "admin.done": "Done",
    "admin.searchBookings": "Search bookings...",
    "admin.client": "Client",
    "admin.expert": "Expert",
    "admin.time": "Time",
    "admin.payment": "Payment",
    "admin.amount": "Amount",
    "admin.view": "View",
    "admin.noBookingsFound": "No bookings found",
    "admin.bookingDetails": "Booking Details",
    "admin.track": "Track",
    "admin.created": "Created",
    "admin.clientNotes": "Client Notes",
    "admin.assignExpert": "Assign Expert",
    "admin.selectExpert": "Select expert",
    "admin.confirm": "Confirm",
    "admin.markComplete": "Mark Complete",
    "admin.manageExperts": "Manage expert profiles, availability, and bookings",
    "admin.addExpert": "Add Expert",
    "admin.noExpertsYet": "No experts yet",
    "admin.rate": "Rate",
    "admin.experience": "Experience",
    "admin.availability": "Availability",
    "admin.scheduleBookings": "Schedule & Bookings",
    "admin.type": "Type",
    "admin.day": "Day",
    "admin.start": "Start",
    "admin.end": "End",
    "admin.action": "Action",
    "admin.recurringWeekly": "Recurring Weekly",
    "admin.specificDate": "Specific Date",
    "admin.recurring": "Recurring",
    "admin.oneTime": "One-time",
    "admin.noAvailability": "No availability slots set",
    "admin.noExpertBookings": "No bookings for this expert",
    "admin.add": "Add",
    "admin.manageMedia": "Manage media content and uploaded files",
    "admin.mediaManagement": "Media Management",
    "admin.addMediaItem": "Add Media Item",
    "admin.fileStorage": "File Storage",
    "admin.duration": "Duration",
    "admin.noMediaItems": "No media items yet",
    "admin.upload": "Upload",
    "admin.uploading": "Uploading…",
    "admin.searchFiles": "Search files…",
    "admin.noFilesFound": "No files matching search",
    "admin.noFilesYet": "No files uploaded yet",
    "admin.dropFiles": "Drop files here",
    "admin.copyUrl": "Copy URL",
    "admin.open": "Open",
    "admin.size": "Size",
    "admin.uploaded": "Uploaded",
    "admin.file": "File",
    "admin.userManagement": "User Management",
    "admin.registeredUsers": "registered users",
    "admin.filterByRole": "Filter by role",
    "admin.allRoles": "All Roles",
    "admin.noRole": "No Role",
    "admin.searchUsers": "Search by name or email…",
    "admin.user": "User",
    "admin.verified": "Verified",
    "admin.pending": "Pending",
    "admin.lastSignIn": "Last Sign In",
    "admin.assignRole": "Assign Role",
    "admin.noUsersFound": "No users found",
    "admin.userDetails": "User Details",
    "admin.unnamedUser": "Unnamed User",
    "admin.emailStatus": "Email Status",
    "admin.joined": "Joined",
    "admin.never": "Never",
    "admin.showing": "Showing",
    "admin.of": "of",
    "admin.prev": "Prev",
    "admin.next": "Next",
    "admin.manageServices": "Manage all service sections displayed on the website",
    "admin.addService": "Add Service",
    "admin.sectors": "Sectors",
    "admin.coreServices": "Core Services",
    "admin.deliverySteps": "Delivery Steps",
    "admin.engagementModels": "Engagement Models",
    "admin.icon": "Icon",
    "admin.titleEN": "Title (EN)",
    "admin.titleAR": "Title (AR)",
    "admin.order": "Order",
    "admin.manageTraining": "Manage bootcamp tracks, modules & webinars",
    "admin.trainingAcademy": "DevWady Academy",
    "admin.addCourse": "Add Course",
    "admin.courses": "Courses",
    "admin.level": "Level",
    "admin.lessons": "Lessons",
    "admin.modules": "Modules",
    "admin.manageHiring": "Manage job postings, freelancers, and recommended talent",
    "admin.hiringManagement": "Hiring Management",
    "admin.jobs": "Jobs",
    "admin.freelancers": "Freelancers",
    "admin.recommended": "Recommended",
    "admin.addJob": "Add Job",
    "admin.location": "Location",
    "admin.tags": "Tags",
    "admin.noJobsYet": "No job postings yet",
    "admin.skills": "Skills",
    "admin.rating": "Rating",
    "admin.alumni": "Alumni",
    "admin.available": "Available",
    "admin.noFreelancersYet": "No freelancer profiles yet",
    "admin.recommendedDesc": "DevWady alumni with rating ≥ 4.5 are automatically shown here.",
    "admin.batch": "Batch",
    "admin.projectsCount": "Projects",
    "admin.noRecommendedYet": "No highly-rated alumni yet",
    "admin.manageTestimonials": "Manage client & graduate testimonials displayed on the site",
    "admin.addTestimonial": "Add Testimonial",
    "admin.section": "Section",
    "admin.noTestimonialsYet": "No testimonials yet",
    "admin.manageGallery": "Manage company timeline and photo gallery",
    "admin.galleryManagement": "Gallery Management",
    "admin.timeline": "Timeline",
    "admin.photos": "Photos",
    "admin.addEvent": "Add Event",
    "admin.period": "Period",
    "admin.noTimelineEvents": "No timeline events",
    "admin.addPhoto": "Add Photo",
    "admin.noPhotos": "No photos",
    "admin.yes": "Yes",
    "admin.no": "No",
    "admin.actionRequired": "Action Required",
    "admin.newMessages": "new messages",
    "admin.pendingBookings": "pending bookings",
    "admin.pendingApplications": "pending applications",
    "admin.totalRevenue": "Total Revenue",
    "admin.revenueThisMonth": "Revenue This Month",
    "admin.revenueAnalytics": "Revenue Analytics",
    "admin.pendingRevenue": "Pending Revenue",
    "admin.avgBookingValue": "Avg Booking Value",
    "admin.conversionRate": "Conversion Rate",
    "admin.noRevenueData": "No revenue data yet — revenue tracking will appear here once payments are processed.",
    "admin.userGrowth": "User Growth",
    "admin.individuals": "Individuals",
    "admin.companies": "Companies",
    "admin.totalUsers": "Total users",
    "admin.thisMonth": "This month",
    "admin.payments": "Payments",
    "admin.monthlyRevenue": "This Month",
    "admin.pendingPayments": "Pending",
    "admin.refunded": "Refunded",
    "admin.transactions": "Transactions",

    // Payments
    "payments.history": "Payment History",
    "payments.totalPaid": "Total Paid",
    "payments.pending": "Pending",
    "payments.thisMonth": "This Month",
    "payments.noPayments": "No payments yet",
    "payments.viewReceipt": "View Receipt",

    // Expert Dashboard
    "expert.dashboard": "Expert Dashboard",
    "expert.notConfigured": "Your expert account is not configured yet. Please contact the admin.",
    "expert.availability": "My Availability",
    "expert.weeklySchedule": "Weekly Schedule",
    "expert.blockedDates": "Blocked Dates",
    "expert.nextAvailable": "Next Available Slots",
    "expert.manageBookings": "Manage Bookings",
    "expert.noBookings": "No bookings found",
    "expert.addMeetingLink": "Add meeting link before the session",
    "expert.anonymousClient": "Anonymous client",
    "expert.registered": "Registered",
    "expert.editProfile": "Edit Profile",

    // Course Detail
    "course.enrollFree": "Enroll for Free",
    "course.enrollPaid": "Enroll",
    "course.continueLearning": "Continue Learning",
    "course.signupToEnroll": "Sign up to Enroll",
    "course.curriculum": "Course Curriculum",
    "course.reviews": "Reviews",
    "course.writeReview": "Write a review",
    "course.submitReview": "Submit Review",
    "course.noReviews": "No reviews yet",
    "course.whatYoullLearn": "What you'll learn",
    "course.instructor": "Instructor",
    "course.preview": "Preview",
    "course.readyToStart": "Ready to Start?",
    "course.enrollNow": "Enroll now and start your learning journey",

    // Learning
    "learn.markComplete": "Mark as Complete",
    "learn.completed": "Completed",
    "learn.previous": "Previous",
    "learn.next": "Next",
    "learn.backToCourse": "Back to course",
    "learn.selectLesson": "Select a lesson to start",
    "learn.congrats": "Congratulations!",
    "learn.attachments": "Attachments",

    // Common
    "common.learnMore": "Learn More",
    "common.readMore": "Read More",
    "common.viewAll": "View All",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.continue": "Continue",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.saving": "Saving...",
    "common.noResults": "No results found",
    "common.all": "All",
    "common.search": "Search...",
    "common.confirm": "Confirm",
    "common.status": "Status",
    "common.date": "Date",
    "common.actions": "Actions",
    "common.details": "Details",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.active": "Active",
    "common.pending": "Pending",
    "common.approved": "Approved",
    "common.rejected": "Rejected",
    "common.completed": "Completed",
    "common.cancelled": "Cancelled",

    // Form
    "form.titleEn": "Title (EN)",
    "form.titleAr": "Title (AR)",
    "form.descEn": "Description (EN)",
    "form.descAr": "Description (AR)",
    "form.slug": "Slug",
    "form.category": "Category",
    "form.section": "Section",
    "form.icon": "Icon",
    "form.featuresEn": "Features (EN)",
    "form.featuresAr": "Features (AR)",
    "form.sortOrder": "Sort Order",
    "form.gradientColor": "Gradient Color",
    "form.linkedin": "LinkedIn",
    "form.github": "GitHub",
    "form.githubUrl": "GitHub URL",
    "form.portfolio": "Portfolio URL",
    "form.budget": "Budget",
    "form.timeline": "Timeline",
    "form.duration": "Duration",

    // Status
    "status.new": "New",
    "status.reviewing": "Under Review",
    "status.quoted": "Quoted",
    "status.inProgress": "In Progress",
    "status.delivered": "Delivered",
    "status.paid": "Paid",
    "status.draft": "Draft",
    "status.published": "Published",

    // Nav - Gateway
    "nav.solutions": "Solutions",
    "nav.enterprise": "Enterprise Solutions",
    "nav.talent": "DevWady Talent",
    "nav.academy": "DevWady Academy",
    "nav.industries": "Industries",
    "nav.buildSoftware": "Build Software",
    "nav.scaleGrow": "Scale & Grow",
    "nav.company": "Company",
    "nav.resources": "Resources",

    // Gateway
    "gateway.heading": "Four Specialized Units, One Trusted Partner",
    "gateway.subtitle": "Each DevWady unit is purpose-built for a specific need",
    "gateway.enterprise.title": "DevWady Enterprise",
    "gateway.enterprise.desc": "Custom software, mobile apps, enterprise systems, and platforms — from concept to launch.",
    "gateway.enterprise.cta": "Start a Project",
    "gateway.talent.title": "DevWady Talent",
    "gateway.talent.desc": "Scale your engineering team with vetted developers — flexible monthly engagements.",
    "gateway.talent.cta": "Build Your Team",
    "gateway.consulting.title": "DevWady Consulting",
    "gateway.consulting.desc": "1-on-1 sessions with senior tech experts — architecture, strategy, code review.",
    "gateway.consulting.cta": "Book an Expert",
    "gateway.academy.title": "DevWady Academy",
    "gateway.academy.desc": "Learn by building real products — practical bootcamps and advanced training.",
    "gateway.academy.cta": "Explore Courses",
    "portfolio.shipped": "Products We've Shipped",

    // Enterprise Portal
    "enterprise.dashboard": "Enterprise Dashboard",
    "enterprise.workspace": "Workspace",
    "enterprise.delivery": "Delivery",
    "enterprise.financeFiles": "Finance & Files",
    "enterprise.company": "Company",
    "enterprise.newRequest": "New Request",
    "enterprise.actionRequired": "Action Required",
    "enterprise.workspaceSettings": "Workspace Settings",
    "enterprise.companyProfile": "Company Profile",
    "enterprise.teamMembers": "Team Members",
    "enterprise.submitRequest": "Submit a Request",
    "enterprise.allCaughtUp": "All caught up — no pending requests at the moment.",
    "enterprise.noProposals": "No proposals waiting — quotes will appear here when prepared.",
    "enterprise.projectsEmpty": "Once you submit a request and we begin, your projects will appear here.",
    "filter.all": "All",
    "filter.active": "Active",
    "filter.completed": "Completed",
    "filter.delivered": "Delivered",
    "filter.new": "New",
    "filter.inReview": "In Review",
    "filter.decided": "Decided",
    "filter.pending": "Pending",
    "filter.closed": "Closed",

    // Talent Portal
    "talent.dashboard": "Talent Dashboard",
    "talent.workspace": "Workspace",
    "talent.recruitment": "Recruitment",
    "talent.engagements": "Engagements",
    "talent.opportunities": "Opportunities",
    "talent.myProfile": "My Profile",
    "talent.browseJobs": "Browse Jobs",
    "talent.browseTalent": "Browse Talent",
    "talent.postJob": "Post Job",
    "talent.shortlists": "Shortlists",
    "talent.hireRequests": "Hire Requests",
    "talent.teamMembers": "Team Members",
    "talent.applications": "Applications",
    "talent.myApplications": "My Applications",
    "talent.portfolio": "Portfolio",
    "talent.preferences": "Preferences",
    "talent.emptyJobs": "Post your first position to start building your talent pipeline.",
    "talent.emptyApps": "Applications will appear here as candidates apply to your positions.",
    "talent.emptyHires": "Hire requests will appear when you engage with shortlisted talent.",
    "talent.freelancerEmpty": "Browse open positions and submit your first application — companies are actively hiring.",

    // Consulting Portal
    "consulting.workspace": "Workspace",
    "consulting.sessions": "Sessions",
    "consulting.earningsProfile": "Earnings & Profile",
    "consulting.mySessions": "My Sessions",
    "consulting.upcomingActive": "Upcoming & Active",
    "consulting.sessionHistory": "Session History",
    "consulting.browseExperts": "Browse Experts",
    "consulting.preferences": "Preferences",
    "consulting.availability": "Availability Schedule",
    "consulting.bookFirstSession": "Book your first expert consultation — browse available specialists and find the right advisor.",
    "consulting.noUpcomingExpert": "Bookings will appear here when clients book sessions.",
    "filter.upcoming": "Upcoming",

    // Academy Portal
    "academy.workspace": "Workspace",
    "academy.myLearning": "My Learning",
    "academy.discover": "Discover",
    "academy.browseCourses": "Browse Courses",
    "academy.teaching": "Teaching",
    "academy.createCourse": "Create Course",
    "academy.lessons": "Lessons",
    "academy.students": "Students",
    "academy.finance": "Finance",
    "academy.earnings": "Earnings",
    "academy.preferences": "Preferences",
    "academy.startLearning": "Start your learning journey — browse our course catalog and enroll in your first course.",
    "academy.noCertsYet": "Certificates will appear here when you complete courses — keep learning!",
    "academy.createFirst": "Create your first course and start sharing your expertise with DevWady learners.",
    "filter.published": "Published",
    "filter.drafts": "Drafts",

    // Backoffice
    "backoffice.title": "Backoffice",
    "backoffice.desc": "DevWady operations across Enterprise, Talent, Consulting, and Academy",
    "backoffice.pendingActions": "Pending Actions",
    "backoffice.accountApprovals": "Account Approvals",
    "backoffice.newRequests": "New Requests",
    "backoffice.pendingBookings": "Pending Bookings",
    "backoffice.instructorApps": "Instructor Apps",
    "backoffice.unreadMessages": "Unread Messages",
    "backoffice.newQuote": "New Quote",
    "backoffice.reviewAccounts": "Review Accounts",
    "backoffice.sendNotification": "Send Notification",
    "backoffice.recentEnterprise": "Recent Enterprise Requests",
    "backoffice.enterprise": "Enterprise",
    "backoffice.talent": "Talent",

    // CTA
    "cta.buildGreat": "Ready to Build Something Great?",
    "cta.readyTitle": "Ready to Start Your Project?",
    "cta.readyDesc": "Get in touch today and receive a free consultation for your project",
    "cta.viewPricing": "View Pricing",

    // Nav — config-driven
    "nav.businessUnits": "Business Units",
    "nav.devwadyBusinessUnits": "DevWady Business Units",
    "nav.forCompanies": "For Companies",
    "nav.forTalent": "For Talent",
    "nav.successStories": "Success Stories",
    "nav.experts": "Experts",
    "nav.courses": "Courses",
    "nav.instructors": "Instructors",
    "nav.whyDevwady": "Why DevWady",
    "nav.myRequests": "My Requests",
    "nav.myProjects": "My Projects",
    "nav.opportunities": "Opportunities",
    "nav.myApplications": "My Applications",
    "nav.mySessions": "My Sessions",
    "nav.availability": "Availability",
    "nav.earnings": "Earnings",
    "nav.myCourses": "My Courses",
    "nav.progress": "Progress",
    "nav.certificates": "Certificates",
    "nav.teaching": "Teaching",
    "nav.students": "Students",
    "nav.users": "Users",
    "nav.operations": "Operations",
    "nav.navigation": "Navigation",

    // CTA — config-driven
    "cta.startProject": "Start Project",
    "cta.bookConsultation": "Book Consultation",
    "cta.postJob": "Post Job",
    "cta.joinAsTalent": "Join as Talent",
    "cta.bookSession": "Book Session",
    "cta.browseExperts": "Browse Experts",
    "cta.exploreCourses": "Explore Courses",
    "cta.applyNow": "Apply Now",
    "cta.goToWorkspace": "Go to Workspace",
    "cta.newRequest": "New Request",
    "cta.talentPortal": "Talent Portal",
    "cta.browseJobs": "Browse Jobs",
    "cta.consultingPortal": "Consulting Portal",
    "cta.updateAvailability": "Update Availability",
    "cta.continueLearning": "Continue Learning",
    "cta.instructorPortal": "Instructor Portal",
    "cta.createCourse": "Create Course",
    "cta.openBackoffice": "Open Backoffice",
  },
  ar: {
    // Nav
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.portfolio": "أعمالنا",
    "nav.training": "أكاديمية ديف وادي",
    "nav.blog": "المدونة",
    "nav.team": "فريقنا",
    "nav.gallery": "المعرض",
    "nav.media": "الوسائط",
    "nav.pricing": "الأسعار",
    "nav.contact": "تواصل معنا",
    "nav.consulting": "الاستشارات",
    "nav.hiring": "التوظيف والمستقلين",
    "nav.more": "المزيد",
    "nav.getStarted": "ابدأ الآن",
    "nav.myProfile": "ملفي الشخصي",
    "nav.editProfile": "تعديل الملف",
    "nav.myBookings": "حجوزاتي",
    "nav.adminPanel": "لوحة التحكم",
    "nav.signOut": "تسجيل الخروج",

    // Hero
    "hero.tagline": "شركة تكنولوجيا وبرمجيات",
    "hero.title1": "خبرة واقعية،",
    "hero.title2": "نقدمها لك.",
    "hero.subtitle": "نصمم ونطور ونوسع أنظمة رقمية متكاملة تقدم قيمة حقيقية. تطبيقات موبايل، مواقع، أنظمة مؤسسية، والمزيد.",
    "hero.cta1": "ابدأ مشروعك",
    "hero.cta2": "استكشف الخدمات",
    "hero.stat1": "+25",
    "hero.stat1Label": "متخصص محترف",
    "hero.stat2": "مصر والسعودية",
    "hero.stat2Label": "مناطق التشغيل",
    "hero.stat3": "3",
    "hero.stat3Label": "قطاعات أعمال",

    // About
    "about.title": "من نحن",
    "about.subtitle": "ديف وادي هي شركة تكنولوجيا وبرمجيات قائمة على المنتجات، مقرها القاهرة، مصر، تعمل في مصر والسعودية.",
    "about.description": "مع أكثر من 25 محترفاً، نصمم ونطور ونوسع أنظمة رقمية متكاملة تقدم قيمة حقيقية. بدأنا كمنظومة بناء — وليس شركة برمجيات تقليدية.",
    "about.vision": "الرؤية",
    "about.visionText": "أن نصبح أكثر شريك تقني موثوق في مصر والسعودية — نبني أنظمة رقمية قابلة للتوسع وننتج كفاءات تقنية جاهزة للسوق.",
    "about.mission": "الرسالة",
    "about.missionText": "نقدم منتجات برمجية حقيقية من البداية للنهاية، ونوفر فرق عمل عالية الأداء من خلال التعهيد، ونسرع نمو الشركات والكفاءات من خلال الاستشارات والتدريب التطبيقي المتقدم.",
    "about.promise": "نبني. نطلق. نوسع.",
    "about.value1": "نقدم قيمة حقيقية",
    "about.value1Desc": "النتائج أهم من المخرجات",
    "about.value2": "الجودة بالتصميم",
    "about.value2Desc": "ضمان الجودة جزء من البناء وليس خطوة أخيرة",
    "about.value3": "عقلية المنتج",
    "about.value3Desc": "فهم السوق قبل كتابة الكود",
    "about.value4": "الشفافية",
    "about.value4Desc": "خطط واضحة، تقدم ملموس، مخاطر محددة",
    "about.value5": "ثقافة النمو",
    "about.value5Desc": "الإرشاد والتعلم والتحسين المستمر",

    // Services
    "services.title": "ماذا نقدم",
    "services.subtitle": "حلول تقنية شاملة عبر ثلاثة قطاعات متصلة",
    "services.delivery": "تطوير البرمجيات",
    "services.deliveryDesc": "منتجات متكاملة من الفكرة إلى الإطلاق مع الجودة في كل خطوة.",
    "services.outsourcing": "التعهيد والتوظيف",
    "services.outsourcingDesc": "وسع فريقك بكفاءات تقنية عالية المستوى بنماذج مرنة.",
    "services.consulting": "الاستشارات والتدريب",
    "services.consultingDesc": "طور بنيتك التقنية ومكن فريقك للمستقبل.",
    "services.mobileApps": "تطبيقات الموبايل",
    "services.mobileAppsDesc": "تطبيقات iOS و Android عالية الأداء — أنظمة متعددة المستخدمين.",
    "services.websites": "المواقع وأنظمة المحتوى",
    "services.websitesDesc": "بوابات مؤسسية ومنصات محتوى مخصصة وتطبيقات ويب.",
    "services.enterprise": "أنظمة المؤسسات",
    "services.enterpriseDesc": "إدارة المدارس، اللوجستيات، نقاط البيع — منصات قوية.",
    "services.uiux": "تصميم واجهات المستخدم",
    "services.uiuxDesc": "رحلات المستخدم، النماذج الأولية، أنظمة التصميم.",
    "services.qa": "ضمان الجودة",
    "services.qaDesc": "اختبار متكامل، اختبارات انحدار، وتدقيق الأداء.",
    "services.itServices": "خدمات تقنية",
    "services.itServicesDesc": "البنية التحتية، السحابة، DevOps، والدعم التقني.",

    // Portfolio
    "portfolio.title": "منتجاتنا ومشاريعنا",
    "portfolio.subtitle": "مجموعة مختارة من المنتجات عبر النقل والخدمات اللوجستية والعقارات والتعليم والمؤسسات.",
    "portfolio.yozya": "منظومة YOZYA",
    "portfolio.yozyaDesc": "منصة متعددة الوحدات — عقارات، سوق خدمات، نقل. تطبيق رئيسي + موقع + منصة شركاء + نظام إدارة.",
    "portfolio.atmodrive": "AtmoDrive",
    "portfolio.atmodriveDesc": "نظام نقل متكامل — تطبيق الراكب، تطبيق السائق، نظام إدارة مع تتبع مباشر ومدفوعات.",
    "portfolio.hamla": "HAMLA",
    "portfolio.hamlaDesc": "منصة لوجستيات البضائع — تطبيق العميل، تطبيق السائق، بوابة الشريك، نظام إدارة.",
    "portfolio.majesty": "مدارس ماجستي الدولية",
    "portfolio.majestyDesc": "نظام إدارة مدرسي متكامل — تطبيق أولياء الأمور، نظام إدارة للدرجات والسلوك والرسوم.",
    "portfolio.nuut": "nuut.ai و nuut POS",
    "portfolio.nuutDesc": "نظام نقاط بيع ذكي للمطاعم — تطبيق العملاء، تطبيق النادل، شاشة المطبخ.",
    "portfolio.flagship": "رئيسي",
    "portfolio.visitWebsite": "زيارة الموقع",
    "portfolio.androidApp": "تطبيق أندرويد",
    "portfolio.iosApp": "تطبيق iOS",
    "portfolio.alliance": "هندسة التحالف",
    "portfolio.allianceDesc": "موقع مؤسسي لخدمات هندسة التحالف العربية — تصميم متجاوب وعرض للخدمات.",
    "portfolio.maamour": "مأمور العربية",
    "portfolio.maamourDesc": "حضور مؤسسي متميز لمأمور العربية — تصميم أنيق وصفحة هبوط متعددة الأقسام.",
    "portfolio.rissad": "رصاد",
    "portfolio.rissadDesc": "منصة رقمية مبنية على تقنيات ويب حديثة — واجهة نظيفة وتصميم متجاوب.",

    // Training
    "training.title": "أكاديمية ديف وادي",
    "training.subtitle": "تعلم بإطلاق منتجات حقيقية",
    "training.description": "برامج تدريبية تطبيقية تنتج محترفين جاهزين للعمل — وليس مجرد حاملي شهادات.",
    "training.methodology": "منهجية «التعلم بالإطلاق»",
    "training.methodDesc": "على عكس التدريب التقليدي الذي ينتهي بشهادة، برامجنا تغمرك في دورات تطوير منتجات حقيقية.",
    "training.step1": "تعلم",
    "training.step1Desc": "المفاهيم الأساسية والأطر وأفضل الممارسات",
    "training.step2": "ابنِ",
    "training.step2Desc": "عمل عملي على ميزات منتج حقيقي",
    "training.step3": "أطلق",
    "training.step3Desc": "انشر في بيئة الإنتاج مع CI/CD",
    "training.step4": "كرر",
    "training.step4Desc": "مراجعات الكود وحلقات التغذية الراجعة",
    "training.android": "تطوير Android الأصلي",
    "training.androidDesc": "Kotlin — ابنِ تطبيقات Android جاهزة للإنتاج (متقدم)",
    "training.ios": "تطوير iOS الأصلي",
    "training.iosDesc": "Swift — ابنِ تطبيقات iOS جاهزة للإنتاج (متقدم)",
    "training.flutter": "Flutter متعدد المنصات",
    "training.flutterDesc": "Dart — ابنِ تطبيقات لـ iOS و Android و Web من كود واحد",
    "training.frontend": "تطوير الواجهات الأمامية",
    "training.frontendDesc": "React و JavaScript — ابنِ تطبيقات ويب تفاعلية حديثة",
    "training.backend": "تطوير الخوادم",
    "training.backendDesc": "PHP و Laravel — صمم بنيات خوادم قابلة للتوسع (متقدم)",
    "training.sdet": "معسكر SDET",
    "training.sdetDesc": "أتمتة الاختبار — أتقن الاختبار الآلي وهندسة الجودة",
    "training.design": "تصميم UI/UX",
    "training.designDesc": "Figma + أنظمة — أنشئ أنظمة تصميم جاهزة للإنتاج",
    "training.devops": "DevOps والسحابة",
    "training.devopsDesc": "AWS و Docker و Kubernetes — ابنِ وانشر البنية التحتية السحابية",
    "training.aiml": "الذكاء الاصطناعي وتعلم الآلة",
    "training.aimlDesc": "Python و TensorFlow و PyTorch — ابنِ تطبيقات ذكية",
    "training.cybersecurity": "أساسيات الأمن السيبراني",
    "training.cybersecurityDesc": "الاختراق الأخلاقي واختبار الاختراق وتدقيق الأمان",
    "training.product": "إدارة المنتجات",
    "training.productDesc": "الاستراتيجية + Agile — قُد المنتجات من الرؤية إلى التسليم",
    "training.corporate": "برامج مؤسسية مخصصة",
    "training.corporateDesc": "برامج مصممة خصيصاً لفريقك",
    "training.enrollNow": "سجل الآن",
    "training.viewCourses": "عرض جميع الدورات",
    "training.weeks": "أسابيع",
    "training.flexible": "مرن",
    "training.whoFor": "لمن هذا البرنامج؟",
    "training.freshGrads": "حديثي التخرج",
    "training.juniorDevs": "المطورين المبتدئين",
    "training.careerSwitchers": "الراغبين في تغيير مسارهم المهني",
    "training.corporateTeams": "فرق الشركات",
    "training.freelancers": "المستقلين",

    // Team
    "team.title": "تعرف على فريقنا",
    "team.subtitle": "المحترفون الموهوبون وراء نجاح DevWady",
    "team.leadership": "القيادة",
    "team.developers": "فريق التطوير",
    "team.trainees": "من متدرب إلى عضو في الفريق",
    "team.traineesDesc": "بدأ هؤلاء المحترفون في أكاديميتنا التدريبية وهم الآن أعضاء بدوام كامل في فريق DevWady — دليل على نجاح نموذج التعلم بالإطلاق.",
    "team.joinUs": "انضم لفريقنا",
    "team.joinUsDesc": "نبحث دائماً عن أفراد موهوبين يشاركوننا شغف بناء منتجات رائعة.",
    "team.applyNow": "قدم الآن",

    // Blog
    "blog.title": "المدونة والرؤى",
    "blog.subtitle": "أفكار حول التكنولوجيا وتطوير المنتجات وبناء الفرق",
    "blog.readMore": "اقرأ المزيد",
    "blog.minRead": "دقيقة قراءة",
    "blog.latest": "أحدث المقالات",
    "blog.categories": "التصنيفات",
    "blog.all": "الكل",
    "blog.tech": "التكنولوجيا",
    "blog.product": "المنتج",
    "blog.culture": "الثقافة",
    "blog.training": "الأكاديمية",

    // Gallery
    "gallery.title": "المعرض والقصة",
    "gallery.subtitle": "رحلتنا من اليوم الأول إلى ما نحن عليه اليوم",
    "gallery.timeline": "مسيرتنا الزمنية",
    "gallery.photos": "الحياة في DevWady",
    "gallery.events": "الأحداث والإنجازات",

    // Media
    "media.title": "الأنشطة الإلكترونية",
    "media.subtitle": "فيديوهات وريلز وبودكاست ومحتوى عن التقنية وثقافة العمل ورؤى الأعمال",
    "media.videos": "فيديوهات وريلز",
    "media.podcasts": "بودكاست",
    "media.techTalks": "محادثات تقنية",
    "media.workLife": "العمل والحياة",
    "media.business": "السوق والأعمال",
    "media.watchNow": "شاهد الآن",
    "media.listenNow": "استمع الآن",

    // Pricing
    "pricing.title": "الأسعار والباقات",
    "pricing.subtitle": "شفافية · مرونة · قابلية للتوسع",
    "pricing.projectBased": "تسليم قائم على المشروع",
    "pricing.projectBasedDesc": "الاكتشاف، تصميم UI/UX، التطوير، ضمان الجودة، النشر والإطلاق",
    "pricing.projectBasedFor": "الأفضل لـ: الإطلاقات الجديدة",
    "pricing.dedicatedSquads": "فرق مخصصة",
    "pricing.dedicatedSquadsDesc": "مطورون متكاملون، متخصصو UI/UX وضمان الجودة، حوكمة Agile مستمرة",
    "pricing.dedicatedSquadsFor": "الأفضل لـ: توسيع المنتجات",
    "pricing.teamAug": "تعزيز الفريق",
    "pricing.teamAugDesc": "كفاءات عالية المستوى عند الطلب، دمج سلس في سير عملك",
    "pricing.teamAugFor": "الأفضل لـ: سد الفجوات المهارية",
    "pricing.consulting": "استشارات دورية",
    "pricing.consultingDesc": "تدقيق البنية والأمان، خارطة طريق المنتج وتخطيط النضج",
    "pricing.consultingFor": "الأفضل لـ: القيادة والاستراتيجية",
    "pricing.contactQuote": "تواصل للحصول على عرض",
    "pricing.requestQuote": "طلب عرض سعر",
    "pricing.popular": "الأكثر شيوعاً",

    // Contact
    "contact.title": "لنبني شيئاً رائعاً معاً",
    "contact.subtitle": "احصل على عرض أسعار تفصيلي لمشروعك خلال 48 ساعة.",
    "contact.name": "الاسم",
    "contact.email": "البريد الإلكتروني",
    "contact.phone": "رقم الهاتف",
    "contact.message": "أخبرنا عن مشروعك",
    "contact.send": "إرسال الرسالة",
    "contact.or": "أو تواصل معنا مباشرة",

    // Footer
    "footer.tagline": "خبرة واقعية، نقدمها لك",
    "footer.rights": "© 2026 DevWady. جميع الحقوق محفوظة.",
    "footer.quickLinks": "روابط سريعة",
    "footer.services": "الخدمات",
    "footer.contactInfo": "معلومات التواصل",
    "footer.followUs": "تابعنا",

    // Profile
    "profile.myBookings": "حجوزاتي",
    "profile.bookingsSubtitle": "تتبع جلساتك الاستشارية",
    "profile.backToProfile": "← ملفي الشخصي",

    // SEO
    "seo.home.title": "DevWady — شركة تكنولوجيا وبرمجيات",
    "seo.home.desc": "نصمم ونطور ونوسع أنظمة رقمية متكاملة عبر مصر والسعودية.",
    "seo.about.title": "من نحن",
    "seo.about.desc": "ديف وادي شركة تكنولوجيا قائمة على المنتجات مقرها القاهرة مع أكثر من 25 محترفاً.",
    "seo.services.title": "خدماتنا",
    "seo.services.desc": "تطبيقات موبايل، مواقع، أنظمة مؤسسية، تصميم واجهات، ضمان جودة، وخدمات تقنية.",
    "seo.portfolio.title": "أعمالنا",
    "seo.portfolio.desc": "منتجات حقيقية بنيناها — YOZYA، AtmoDrive، HAMLA، والمزيد.",
    "seo.training.title": "أكاديمية ديف وادي",
    "seo.training.desc": "مسارات تدريبية تطبيقية يقودها محترفون من الصناعة.",
    "seo.blog.title": "المدونة",
    "seo.blog.desc": "رؤى تقنية وقصص منتجات وثقافة الشركة من فريق ديف وادي.",
    "seo.team.title": "فريقنا",
    "seo.team.desc": "تعرف على المحترفين خلف ديف وادي.",
    "seo.consulting.title": "استشارات الخبراء",
    "seo.consulting.desc": "احجز جلسات فردية مع خبراء تقنيين كبار.",
    "seo.hiring.title": "التوظيف والمستقلين",
    "seo.hiring.desc": "اعثر على أفضل الكفاءات التقنية أو تصفح الوظائف المتاحة.",
    "seo.pricing.title": "الأسعار",
    "seo.pricing.desc": "نماذج تعاقد مرنة لمشاريع بأي حجم.",
    "seo.contact.title": "تواصل معنا",
    "seo.contact.desc": "تواصل معنا للحصول على استشارة مجانية.",
    "seo.gallery.title": "المعرض",
    "seo.gallery.desc": "رحلتنا ومعالمنا.",
    "seo.media.title": "الوسائط",
    "seo.media.desc": "فيديوهات وبودكاست وظهور إعلامي.",
    "seo.login.title": "تسجيل الدخول",
    "seo.signup.title": "إنشاء حساب",
    "seo.forgotPassword.title": "نسيت كلمة المرور",
    "seo.resetPassword.title": "إعادة تعيين كلمة المرور",
    "seo.notFound.title": "الصفحة غير موجودة",
    "seo.profile.title": "ملفي الشخصي",
    "seo.profileEdit.title": "تعديل الملف الشخصي",
    "seo.profileBookings.title": "حجوزاتي",
    "seo.profileApplications.title": "طلباتي",
    "seo.consultingRequest.title": "حجز استشارة",
    "seo.consultingTrack.title": "تتبع الحجز",
    "seo.onboarding.title": "ابدأ الآن",
    "seo.companyDashboard.title": "لوحة الشركة",
    "seo.companyProfile.title": "ملف الشركة",
    "seo.companyJobs.title": "وظائفي",
    "seo.companyShortlists.title": "المواهب المفضلة",
    "seo.companyTalent.title": "تصفح المواهب",

    // Admin
    "admin.console": "لوحة التحكم",
    "admin.dashboard": "الرئيسية",
    "admin.blogPosts": "المقالات",
    "admin.portfolio": "الأعمال",
    "admin.services": "الخدمات",
    "admin.teamMembers": "أعضاء الفريق",
    "admin.testimonials": "الشهادات",
    "admin.training": "الأكاديمية",
    "admin.hiring": "التوظيف",
    "admin.engagements": "التعاقدات",
    "admin.experts": "الخبراء",
    "admin.bookings": "الحجوزات",
    "admin.contacts": "صندوق الرسائل",
    "admin.serviceRequests": "طلبات الخدمة",
    "admin.quotes": "عروض الأسعار",
    "admin.projectTracking": "المشاريع",
    "admin.media": "مكتبة الوسائط",
    "admin.gallery": "المعرض",
    "admin.users": "المستخدمين",
    "admin.content": "المحتوى",
    "admin.operations": "العمليات",
    "admin.backToSite": "العودة للموقع",
    "admin.signOut": "تسجيل الخروج",
    "admin.create": "إنشاء",
    "admin.edit": "تعديل",
    "admin.delete": "حذف",
    "admin.save": "حفظ",
    "admin.cancel": "إلغاء",
    "admin.search": "بحث",
    "admin.filter": "تصفية",
    "admin.noData": "لا توجد بيانات",
    "admin.overview": "نظرة عامة",
    "admin.submissions": "الطلبات المقدمة",
    "admin.refresh": "تحديث",
    "admin.actions": "إجراءات",
    "admin.status": "الحالة",
    "admin.active": "نشط",
    "admin.inactive": "غير نشط",
    "admin.loading": "جاري التحميل…",
    "admin.welcomeBack": "مرحباً بعودتك",
    "admin.commandCenter": "مركز التحكم",
    "admin.liveNow": "متصل الآن",
    "admin.liveVisitors": "الزوار المباشرون",
    "admin.viewsToday": "المشاهدات اليوم",
    "admin.uniqueVisitors": "الزوار الفريدون",
    "admin.views7d": "المشاهدات (7 أيام)",
    "admin.trafficOverview": "نظرة على الزيارات",
    "admin.last7days": "آخر 7 أيام",
    "admin.topPages": "أكثر الصفحات زيارة",
    "admin.noPageViews": "لا توجد مشاهدات بعد",
    "admin.recentBookings": "أحدث الحجوزات",
    "admin.noBookings": "لا توجد حجوزات بعد",
    "admin.recentMessages": "أحدث الرسائل",
    "admin.noMessages": "لا توجد رسائل بعد",
    "admin.months6": "6 أشهر",
    "admin.dateRange": "النطاق الزمني",
    "admin.last7Days": "آخر 7 أيام",
    "admin.last30Days": "آخر 30 يوم",
    "admin.last3Months": "آخر 3 أشهر",
    "admin.last6Months": "آخر 6 أشهر",
    "admin.thisYear": "هذا العام",
    "admin.allTime": "كل الوقت",
    "admin.platformOverview": "نظرة على المنصة",
    "admin.exportCSV": "تصدير CSV",
    "admin.downloadReport": "تحميل التقرير",
    "admin.notificationCenter": "مركز الإشعارات",
    "admin.sendBroadcast": "إرسال بث",
    "admin.targetAudience": "الجمهور المستهدف",
    "admin.allUsers": "جميع المستخدمين",
    "admin.allIndividuals": "جميع الأفراد",
    "admin.allCompanies": "جميع الشركات",
    "admin.allAdmins": "جميع المشرفين",
    "admin.totalNotifications": "إجمالي المرسلة",
    "admin.unreadNotifications": "غير مقروءة",
    "admin.notificationsToday": "اليوم",
    "admin.mostActiveType": "النوع الأكثر نشاطاً",
    "admin.notificationsSent": "تم إرسال الإشعارات",
    "notifications.title": "الإشعارات",
    "notifications.markAllRead": "تعليم الكل كمقروء",
    "notifications.empty": "لا توجد إشعارات بعد",
    "notifications.viewAll": "عرض جميع الإشعارات",
    "notifications.tabAll": "الكل",
    "notifications.tabUnread": "غير مقروء",
    "notifications.tabBookings": "الحجوزات",
    "notifications.tabJobs": "الوظائف",
    "notifications.tabSystem": "النظام",
    "notifications.noNotifications": "لا توجد إشعارات",
    "notifications.allCaughtUp": "لقد اطلعت على كل شيء!",
    "notifications.viewDetails": "عرض التفاصيل",
    "notifications.loadMore": "تحميل المزيد",
    "notifications.markRead": "تعليم كمقروء",
    "admin.quickAccess": "وصول سريع",
    "admin.viewAll": "عرض الكل",
    "admin.projects": "المشاريع",
    "admin.team": "الفريق",
    "admin.messages": "الرسائل",
    "admin.administrator": "مدير النظام",
    "admin.searchPlaceholder": "بحث...",
    "admin.manageContent": "إدارة محتوى المدونة",
    "admin.newPost": "مقال جديد",
    "admin.noPostsYet": "لا توجد مقالات بعد",
    "admin.title": "العنوان",
    "admin.category": "التصنيف",
    "admin.date": "التاريخ",
    "admin.managePortfolio": "إدارة سجل الأعمال",
    "admin.newProject": "مشروع جديد",
    "admin.noProjectsYet": "لا توجد مشاريع بعد",
    "admin.featured": "مميز",
    "admin.manageTeam": "إدارة فريقك",
    "admin.addMember": "إضافة عضو",
    "admin.noMembersYet": "لا يوجد أعضاء في الفريق بعد",
    "admin.name": "الاسم",
    "admin.role": "الدور",
    "admin.department": "القسم",
    "admin.manageContacts": "إدارة الرسائل الواردة من نموذج التواصل",
    "admin.searchContacts": "بحث بالاسم أو البريد أو الموضوع…",
    "admin.selected": "محدد",
    "admin.markRead": "تحديد كمقروء",
    "admin.markReplied": "تحديد كمُجاب",
    "admin.archive": "أرشفة",
    "admin.from": "من",
    "admin.subject": "الموضوع",
    "admin.noMessagesFound": "لا توجد رسائل",
    "admin.messageFrom": "رسالة من",
    "admin.email": "البريد الإلكتروني",
    "admin.phone": "الهاتف",
    "admin.message": "الرسالة",
    "admin.updateStatus": "تحديث الحالة",
    "admin.adminNotes": "ملاحظات المدير",
    "admin.addNotes": "أضف ملاحظات داخلية حول هذا الطلب…",
    "admin.saveNotes": "حفظ الملاحظات",
    "admin.saving": "جاري الحفظ…",
    "admin.received": "تم الاستلام",
    "admin.manageBookings": "إدارة حجوزات جلسات الاستشارة والطلبات الجديدة",
    "admin.bookingsRequests": "الحجوزات والطلبات",
    "admin.total": "الإجمالي",
    "admin.newRequests": "طلبات جديدة",
    "admin.confirmed": "مؤكد",
    "admin.completed": "مكتمل",
    "admin.cancelled": "ملغي",
    "admin.requests": "الطلبات",
    "admin.done": "تم",
    "admin.searchBookings": "بحث في الحجوزات...",
    "admin.client": "العميل",
    "admin.expert": "الخبير",
    "admin.time": "الوقت",
    "admin.payment": "الدفع",
    "admin.amount": "المبلغ",
    "admin.view": "عرض",
    "admin.noBookingsFound": "لا توجد حجوزات",
    "admin.bookingDetails": "تفاصيل الحجز",
    "admin.track": "المسار",
    "admin.created": "تم الإنشاء",
    "admin.clientNotes": "ملاحظات العميل",
    "admin.assignExpert": "تعيين خبير",
    "admin.selectExpert": "اختر خبيراً",
    "admin.confirm": "تأكيد",
    "admin.markComplete": "تحديد كمكتمل",
    "admin.manageExperts": "إدارة ملفات الخبراء والتوفر والحجوزات",
    "admin.addExpert": "إضافة خبير",
    "admin.noExpertsYet": "لا يوجد خبراء بعد",
    "admin.rate": "السعر",
    "admin.experience": "الخبرة",
    "admin.availability": "التوفر",
    "admin.scheduleBookings": "الجدول والحجوزات",
    "admin.type": "النوع",
    "admin.day": "اليوم",
    "admin.start": "البداية",
    "admin.end": "النهاية",
    "admin.action": "إجراء",
    "admin.recurringWeekly": "أسبوعي متكرر",
    "admin.specificDate": "تاريخ محدد",
    "admin.recurring": "متكرر",
    "admin.oneTime": "مرة واحدة",
    "admin.noAvailability": "لا توجد فترات توفر محددة",
    "admin.noExpertBookings": "لا توجد حجوزات لهذا الخبير",
    "admin.add": "إضافة",
    "admin.manageMedia": "إدارة المحتوى الإعلامي والملفات المرفوعة",
    "admin.mediaManagement": "إدارة الوسائط",
    "admin.addMediaItem": "إضافة عنصر وسائط",
    "admin.fileStorage": "تخزين الملفات",
    "admin.duration": "المدة",
    "admin.noMediaItems": "لا توجد عناصر وسائط بعد",
    "admin.upload": "رفع",
    "admin.uploading": "جاري الرفع…",
    "admin.searchFiles": "بحث في الملفات…",
    "admin.noFilesFound": "لا توجد ملفات مطابقة",
    "admin.noFilesYet": "لم يتم رفع ملفات بعد",
    "admin.dropFiles": "اسحب الملفات هنا",
    "admin.copyUrl": "نسخ الرابط",
    "admin.open": "فتح",
    "admin.size": "الحجم",
    "admin.uploaded": "تم الرفع",
    "admin.file": "ملف",
    "admin.userManagement": "إدارة المستخدمين",
    "admin.registeredUsers": "مستخدم مسجل",
    "admin.filterByRole": "تصفية حسب الدور",
    "admin.allRoles": "جميع الأدوار",
    "admin.noRole": "بدون دور",
    "admin.searchUsers": "بحث بالاسم أو البريد…",
    "admin.user": "المستخدم",
    "admin.verified": "موثق",
    "admin.pending": "قيد الانتظار",
    "admin.lastSignIn": "آخر تسجيل دخول",
    "admin.assignRole": "تعيين دور",
    "admin.noUsersFound": "لا يوجد مستخدمون",
    "admin.userDetails": "تفاصيل المستخدم",
    "admin.unnamedUser": "مستخدم بدون اسم",
    "admin.emailStatus": "حالة البريد",
    "admin.joined": "تاريخ الانضمام",
    "admin.never": "لم يسجل دخولاً",
    "admin.showing": "عرض",
    "admin.of": "من",
    "admin.prev": "السابق",
    "admin.next": "التالي",
    "admin.manageServices": "إدارة جميع أقسام الخدمات المعروضة على الموقع",
    "admin.addService": "إضافة خدمة",
    "admin.sectors": "القطاعات",
    "admin.coreServices": "الخدمات الأساسية",
    "admin.deliverySteps": "خطوات التسليم",
    "admin.engagementModels": "نماذج التعاقد",
    "admin.icon": "الأيقونة",
    "admin.titleEN": "العنوان (EN)",
    "admin.titleAR": "العنوان (AR)",
    "admin.order": "الترتيب",
    "admin.manageTraining": "إدارة مسارات البوتكامب والوحدات والندوات",
    "admin.trainingAcademy": "أكاديمية ديف وادي",
    "admin.addCourse": "إضافة دورة",
    "admin.courses": "الدورات",
    "admin.level": "المستوى",
    "admin.lessons": "الدروس",
    "admin.modules": "الوحدات",
    "admin.manageHiring": "إدارة إعلانات الوظائف والمستقلين والمواهب الموصى بها",
    "admin.hiringManagement": "إدارة التوظيف",
    "admin.jobs": "الوظائف",
    "admin.freelancers": "المستقلون",
    "admin.recommended": "الموصى بهم",
    "admin.addJob": "إضافة وظيفة",
    "admin.location": "الموقع",
    "admin.tags": "الوسوم",
    "admin.noJobsYet": "لا توجد وظائف بعد",
    "admin.skills": "المهارات",
    "admin.rating": "التقييم",
    "admin.alumni": "خريج",
    "admin.available": "متاح",
    "admin.noFreelancersYet": "لا توجد ملفات مستقلين بعد",
    "admin.recommendedDesc": "خريجو ديف وادي بتقييم ≥ 4.5 يظهرون تلقائياً هنا.",
    "admin.batch": "الدفعة",
    "admin.projectsCount": "المشاريع",
    "admin.noRecommendedYet": "لا يوجد خريجون بتقييم عالٍ بعد",
    "admin.manageTestimonials": "إدارة شهادات العملاء والخريجين المعروضة على الموقع",
    "admin.addTestimonial": "إضافة شهادة",
    "admin.section": "القسم",
    "admin.noTestimonialsYet": "لا توجد شهادات بعد",
    "admin.manageGallery": "إدارة الجدول الزمني للشركة ومعرض الصور",
    "admin.galleryManagement": "إدارة المعرض",
    "admin.timeline": "الجدول الزمني",
    "admin.photos": "الصور",
    "admin.addEvent": "إضافة حدث",
    "admin.period": "الفترة",
    "admin.noTimelineEvents": "لا توجد أحداث في الجدول الزمني",
    "admin.addPhoto": "إضافة صورة",
    "admin.noPhotos": "لا توجد صور",
    "admin.yes": "نعم",
    "admin.no": "لا",
    "admin.actionRequired": "إجراءات مطلوبة",
    "admin.newMessages": "رسائل جديدة",
    "admin.pendingBookings": "حجوزات معلقة",
    "admin.pendingApplications": "طلبات معلقة",
    "admin.totalRevenue": "إجمالي الإيرادات",
    "admin.revenueThisMonth": "إيرادات هذا الشهر",
    "admin.revenueAnalytics": "تحليلات الإيرادات",
    "admin.pendingRevenue": "إيرادات معلقة",
    "admin.avgBookingValue": "متوسط قيمة الحجز",
    "admin.conversionRate": "معدل التحويل",
    "admin.noRevenueData": "لا توجد بيانات إيرادات بعد — ستظهر هنا بمجرد معالجة المدفوعات.",
    "admin.userGrowth": "نمو المستخدمين",
    "admin.individuals": "أفراد",
    "admin.companies": "شركات",
    "admin.totalUsers": "إجمالي المستخدمين",
    "admin.thisMonth": "هذا الشهر",
    "admin.payments": "المدفوعات",
    "admin.monthlyRevenue": "هذا الشهر",
    "admin.pendingPayments": "معلقة",
    "admin.refunded": "مسترد",
    "admin.transactions": "المعاملات",

    // Payments
    "payments.history": "سجل المدفوعات",
    "payments.totalPaid": "إجمالي المدفوع",
    "payments.pending": "معلقة",
    "payments.thisMonth": "هذا الشهر",
    "payments.noPayments": "لا توجد مدفوعات بعد",
    "payments.viewReceipt": "عرض الإيصال",

    // Expert Dashboard
    "expert.dashboard": "لوحة تحكم الخبير",
    "expert.notConfigured": "لم يتم إعداد حساب الخبير بعد. يرجى التواصل مع المسؤول.",
    "expert.availability": "جدول التوفر",
    "expert.weeklySchedule": "الجدول الأسبوعي",
    "expert.blockedDates": "تواريخ محظورة",
    "expert.nextAvailable": "المواعيد القادمة المتاحة",
    "expert.manageBookings": "إدارة الحجوزات",
    "expert.noBookings": "لا توجد حجوزات",
    "expert.addMeetingLink": "أضف رابط الاجتماع قبل الجلسة",
    "expert.anonymousClient": "عميل مجهول",
    "expert.registered": "مسجل",
    "expert.editProfile": "تعديل الملف الشخصي",

    // Course Detail
    "course.enrollFree": "سجل مجاناً",
    "course.enrollPaid": "سجل",
    "course.continueLearning": "متابعة التعلم",
    "course.signupToEnroll": "سجل للتسجيل",
    "course.curriculum": "محتوى الدورة",
    "course.reviews": "التقييمات",
    "course.writeReview": "اكتب تقييماً",
    "course.submitReview": "إرسال التقييم",
    "course.noReviews": "لا توجد تقييمات بعد",
    "course.whatYoullLearn": "ماذا ستتعلم",
    "course.instructor": "المدرب",
    "course.preview": "معاينة",
    "course.readyToStart": "جاهز للبدء؟",
    "course.enrollNow": "سجل الآن وابدأ رحلتك",

    // Learning
    "learn.markComplete": "تحديد كمكتمل",
    "learn.completed": "مكتمل",
    "learn.previous": "السابق",
    "learn.next": "التالي",
    "learn.backToCourse": "العودة للدورة",
    "learn.selectLesson": "اختر درساً للبدء",
    "learn.congrats": "تهانينا!",
    "learn.attachments": "المرفقات",

    // Common
    "common.learnMore": "اعرف المزيد",
    "common.readMore": "اقرأ المزيد",
    "common.viewAll": "عرض الكل",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.back": "العودة",
    "common.next": "التالي",
    "common.continue": "متابعة",
    "common.submit": "إرسال",
    "common.close": "إغلاق",
    "common.loading": "جاري التحميل...",
    "common.saving": "جاري الحفظ...",
    "common.noResults": "لا توجد نتائج",
    "common.all": "الكل",
    "common.search": "بحث...",
    "common.confirm": "تأكيد",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.actions": "الإجراءات",
    "common.details": "التفاصيل",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.active": "نشط",
    "common.pending": "قيد الانتظار",
    "common.approved": "موافق عليه",
    "common.rejected": "مرفوض",
    "common.completed": "مكتمل",
    "common.cancelled": "ملغي",

    // Form
    "form.titleEn": "العنوان (EN)",
    "form.titleAr": "العنوان (AR)",
    "form.descEn": "الوصف (EN)",
    "form.descAr": "الوصف (AR)",
    "form.slug": "المعرّف",
    "form.category": "التصنيف",
    "form.section": "القسم",
    "form.icon": "الأيقونة",
    "form.featuresEn": "المميزات (EN)",
    "form.featuresAr": "المميزات (AR)",
    "form.sortOrder": "ترتيب العرض",
    "form.gradientColor": "لون التدرج",
    "form.linkedin": "لينكد إن",
    "form.github": "جيت هب",
    "form.githubUrl": "رابط جيت هب",
    "form.portfolio": "رابط الأعمال",
    "form.budget": "الميزانية",
    "form.timeline": "الجدول الزمني",
    "form.duration": "المدة",

    // Status
    "status.new": "جديد",
    "status.reviewing": "قيد المراجعة",
    "status.quoted": "تم التسعير",
    "status.inProgress": "قيد التنفيذ",
    "status.delivered": "تم التسليم",
    "status.paid": "مدفوع",
    "status.draft": "مسودة",
    "status.published": "منشور",

    // CTA
    // Nav - Gateway
    "nav.solutions": "حلولنا",
    "nav.enterprise": "حلول المؤسسات",
    "nav.talent": "مواهب ديف وادي",
    "nav.academy": "أكاديمية ديف وادي",
    "nav.industries": "القطاعات",
    "nav.buildSoftware": "بناء البرمجيات",
    "nav.scaleGrow": "وسّع ونمو",
    "nav.company": "الشركة",
    "nav.resources": "موارد",

    // Gateway
    "gateway.heading": "أربع وحدات متخصصة، شريك واحد موثوق",
    "gateway.subtitle": "كل وحدة في ديف وادي مصممة لاحتياج محدد",
    "gateway.enterprise.title": "ديف وادي إنتربرايز",
    "gateway.enterprise.desc": "برمجيات مخصصة، تطبيقات جوال، أنظمة مؤسسية ومنصات — من الفكرة إلى الإطلاق.",
    "gateway.enterprise.cta": "ابدأ مشروعك",
    "gateway.talent.title": "ديف وادي تالنت",
    "gateway.talent.desc": "وسّع فريقك الهندسي بمطورين معتمدين — عقود شهرية مرنة.",
    "gateway.talent.cta": "بناء فريقك",
    "gateway.consulting.title": "ديف وادي للاستشارات",
    "gateway.consulting.desc": "جلسات فردية مع خبراء تقنيين — هندسة، استراتيجية، مراجعة كود.",
    "gateway.consulting.cta": "احجز مع خبير",
    "gateway.academy.title": "أكاديمية ديف وادي",
    "gateway.academy.desc": "تعلم ببناء منتجات حقيقية — معسكرات تدريبية عملية ومتقدمة.",
    "gateway.academy.cta": "استكشف الدورات",
    "portfolio.shipped": "منتجات أطلقناها",

    // Enterprise Portal
    "enterprise.dashboard": "لوحة تحكم إنتربرايز",
    "enterprise.workspace": "مساحة العمل",
    "enterprise.delivery": "التسليمات",
    "enterprise.financeFiles": "المالية والملفات",
    "enterprise.company": "الشركة",
    "enterprise.newRequest": "طلب جديد",
    "enterprise.actionRequired": "بحاجة لإجراء",
    "enterprise.workspaceSettings": "إعدادات مساحة العمل",
    "enterprise.companyProfile": "ملف الشركة",
    "enterprise.teamMembers": "أعضاء الفريق",
    "enterprise.submitRequest": "قدّم طلباً",
    "enterprise.allCaughtUp": "كل شيء مُحدَّث — لا توجد طلبات معلقة حالياً.",
    "enterprise.noProposals": "لا توجد عروض بانتظارك — ستظهر هنا عند تجهيزها.",
    "enterprise.projectsEmpty": "بمجرد تقديم طلب وبدء العمل، ستظهر مشاريعك هنا.",
    "filter.all": "الكل",
    "filter.active": "نشطة",
    "filter.completed": "مكتملة",
    "filter.delivered": "مسلّمة",
    "filter.new": "جديدة",
    "filter.inReview": "قيد المراجعة",
    "filter.decided": "تم البت",
    "filter.pending": "قيد الانتظار",
    "filter.closed": "مغلقة",

    // Talent Portal
    "talent.dashboard": "لوحة تحكم المواهب",
    "talent.workspace": "مساحة العمل",
    "talent.recruitment": "التوظيف",
    "talent.engagements": "العقود",
    "talent.opportunities": "الفرص",
    "talent.myProfile": "ملفي الشخصي",
    "talent.browseJobs": "تصفح الوظائف",
    "talent.browseTalent": "تصفح المواهب",
    "talent.postJob": "نشر وظيفة",
    "talent.shortlists": "القوائم المختصرة",
    "talent.hireRequests": "طلبات التوظيف",
    "talent.teamMembers": "أعضاء الفريق",
    "talent.applications": "الطلبات",
    "talent.myApplications": "طلباتي",
    "talent.portfolio": "أعمالي",
    "talent.preferences": "التفضيلات",
    "talent.emptyJobs": "انشر وظيفتك الأولى لبدء بناء خط المواهب.",
    "talent.emptyApps": "ستظهر الطلبات هنا عندما يتقدم المرشحون لوظائفك.",
    "talent.emptyHires": "ستظهر طلبات التوظيف عند التعاقد مع المواهب المختارة.",
    "talent.freelancerEmpty": "تصفح الوظائف المتاحة وقدّم طلبك الأول — الشركات توظف الآن.",

    // Consulting Portal
    "consulting.workspace": "مساحة العمل",
    "consulting.sessions": "الجلسات",
    "consulting.earningsProfile": "الأرباح والملف",
    "consulting.mySessions": "جلساتي",
    "consulting.upcomingActive": "القادمة والنشطة",
    "consulting.sessionHistory": "سجل الجلسات",
    "consulting.browseExperts": "تصفح الخبراء",
    "consulting.preferences": "التفضيلات",
    "consulting.availability": "جدول التوافر",
    "consulting.bookFirstSession": "احجز أول استشارة مع خبير — تصفح المتخصصين المتاحين وجد المستشار المناسب.",
    "consulting.noUpcomingExpert": "ستظهر الحجوزات هنا عندما يحجز العملاء جلسات.",
    "filter.upcoming": "القادمة",

    // Academy Portal
    "academy.workspace": "مساحة العمل",
    "academy.myLearning": "تعلّمي",
    "academy.discover": "اكتشف",
    "academy.browseCourses": "تصفح الدورات",
    "academy.teaching": "التدريس",
    "academy.createCourse": "إنشاء دورة",
    "academy.lessons": "الدروس",
    "academy.students": "الطلاب",
    "academy.finance": "المالية",
    "academy.earnings": "الأرباح",
    "academy.preferences": "التفضيلات",
    "academy.startLearning": "ابدأ رحلة تعلمك — تصفح كتالوج الدورات وسجل في أول دورة.",
    "academy.noCertsYet": "ستظهر الشهادات هنا عند إكمال الدورات — واصل التعلم!",
    "academy.createFirst": "أنشئ دورتك الأولى وابدأ مشاركة خبراتك مع متعلمي ديف وادي.",
    "filter.published": "منشورة",
    "filter.drafts": "مسودات",

    // Backoffice
    "backoffice.title": "الإدارة",
    "backoffice.desc": "عمليات ديف وادي عبر إنتربرايز وتالنت والاستشارات والأكاديمية",
    "backoffice.pendingActions": "إجراءات معلقة",
    "backoffice.accountApprovals": "موافقات الحسابات",
    "backoffice.newRequests": "طلبات جديدة",
    "backoffice.pendingBookings": "حجوزات معلقة",
    "backoffice.instructorApps": "طلبات معلمين",
    "backoffice.unreadMessages": "رسائل غير مقروءة",
    "backoffice.newQuote": "إنشاء عرض سعر",
    "backoffice.reviewAccounts": "مراجعة الحسابات",
    "backoffice.sendNotification": "إرسال إشعار",
    "backoffice.recentEnterprise": "طلبات إنتربرايز الأخيرة",
    "backoffice.enterprise": "إنتربرايز",
    "backoffice.talent": "تالنت",

    // CTA
    "cta.buildGreat": "جاهز تبني شيئاً عظيماً؟",
    "cta.readyTitle": "جاهز تبدأ مشروعك؟",
    "cta.readyDesc": "تواصل معنا اليوم واحصل على استشارة مجانية لمشروعك",
    "cta.viewPricing": "عرض الأسعار",

    // Nav — config-driven
    "nav.businessUnits": "وحدات الأعمال",
    "nav.devwadyBusinessUnits": "وحدات أعمال ديف وادي",
    "nav.forCompanies": "للشركات",
    "nav.forTalent": "للمواهب",
    "nav.successStories": "قصص النجاح",
    "nav.experts": "الخبراء",
    "nav.courses": "الدورات",
    "nav.instructors": "المعلمون",
    "nav.whyDevwady": "لماذا ديف وادي",
    "nav.myRequests": "طلباتي",
    "nav.myProjects": "مشاريعي",
    "nav.opportunities": "الفرص",
    "nav.myApplications": "طلباتي",
    "nav.mySessions": "جلساتي",
    "nav.availability": "التوافر",
    "nav.earnings": "الأرباح",
    "nav.myCourses": "دوراتي",
    "nav.progress": "التقدم",
    "nav.certificates": "الشهادات",
    "nav.teaching": "التدريس",
    "nav.students": "الطلاب",
    "nav.users": "المستخدمون",
    "nav.operations": "العمليات",
    "nav.navigation": "التنقل",

    // CTA — config-driven
    "cta.startProject": "ابدأ مشروعك",
    "cta.bookConsultation": "احجز استشارة",
    "cta.postJob": "انشر وظيفة",
    "cta.joinAsTalent": "انضم كموهبة",
    "cta.bookSession": "احجز جلسة",
    "cta.browseExperts": "تصفح الخبراء",
    "cta.exploreCourses": "استكشف الدورات",
    "cta.applyNow": "قدّم الآن",
    "cta.goToWorkspace": "افتح مساحة العمل",
    "cta.newRequest": "طلب جديد",
    "cta.talentPortal": "بوابة المواهب",
    "cta.browseJobs": "تصفح الوظائف",
    "cta.consultingPortal": "بوابة الاستشارات",
    "cta.updateAvailability": "تحديث التوافر",
    "cta.continueLearning": "تابع التعلم",
    "cta.instructorPortal": "بوابة المعلم",
    "cta.createCourse": "إنشاء دورة",
    "cta.openBackoffice": "افتح الإدارة",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("devwady-lang");
    return (saved as Lang) || "en";
  });

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("devwady-lang", lang);
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
