
-- Seed all 12 training courses
INSERT INTO public.training_courses (slug, icon, emoji, color, title_en, title_ar, description_en, description_ar, duration_en, duration_ar, level_en, level_ar, total_lessons, total_projects, outcomes_en, outcomes_ar, tools, sort_order) VALUES
('android', 'Smartphone', '📱', 'from-green-500 to-emerald-600', 'Native Android Development (Advanced)', 'تطوير Android الأصلي (متقدم)', 'Native & cross-platform mobile apps', 'تطبيقات موبايل أصلية ومتعددة المنصات', '10 Weeks', '10 أسابيع', 'Advanced', 'متقدم', 48, 3,
  ARRAY['Build native Android apps with Kotlin','Jetpack Compose & MVVM','Publish to Google Play'],
  ARRAY['بناء تطبيقات Android أصلية بـ Kotlin','Jetpack Compose و MVVM','نشر على Google Play'],
  ARRAY['Kotlin','Jetpack Compose','Room DB','Retrofit'], 1),
('ios', 'Smartphone', '🍎', 'from-blue-500 to-indigo-600', 'Native iOS Development (Advanced)', 'تطوير iOS الأصلي (متقدم)', 'Native iOS apps with Swift & SwiftUI', 'تطبيقات iOS أصلية بـ Swift و SwiftUI', '10 Weeks', '10 أسابيع', 'Advanced', 'متقدم', 46, 3,
  ARRAY['Build native iOS apps with Swift','SwiftUI & UIKit','Publish to App Store'],
  ARRAY['بناء تطبيقات iOS أصلية بـ Swift','SwiftUI و UIKit','نشر على App Store'],
  ARRAY['Swift','SwiftUI','Core Data','Xcode'], 2),
('flutter', 'Layers', '🦋', 'from-cyan-500 to-blue-500', 'Flutter Cross-Platform', 'Flutter متعدد المنصات', 'Build cross-platform apps from one codebase', 'بناء تطبيقات متعددة المنصات بكود واحد', '12 Weeks', '12 أسبوع', 'Beginner → Advanced', 'مبتدئ → متقدم', 56, 3,
  ARRAY['Build cross-platform apps from one codebase','API & Firebase integration','Deploy to iOS, Android & Web'],
  ARRAY['بناء تطبيقات متعددة المنصات بكود واحد','تكامل API و Firebase','نشر على iOS و Android و Web'],
  ARRAY['Flutter','Dart','Firebase','REST APIs'], 3),
('frontend', 'MonitorSmartphone', '🖥️', 'from-sky-500 to-blue-500', 'Frontend Development — React & JS', 'تطوير الواجهات الأمامية — React و JS', 'Master modern JavaScript & React', 'إتقان JavaScript الحديث و React', '10 Weeks', '10 أسابيع', 'Beginner → Intermediate', 'مبتدئ → متوسط', 50, 3,
  ARRAY['Master modern JavaScript','Build interactive React apps','State management & routing'],
  ARRAY['إتقان JavaScript الحديث','بناء تطبيقات React تفاعلية','إدارة الحالة و Routing'],
  ARRAY['React','JavaScript','TypeScript','Tailwind CSS'], 4),
('backend', 'Server', '⚙️', 'from-orange-500 to-red-500', 'Backend Development — PHP & Laravel (Advanced)', 'تطوير الخوادم — PHP و Laravel (متقدم)', 'Build scalable REST APIs with Laravel', 'بناء APIs قابلة للتوسع بـ Laravel', '10 Weeks', '10 أسابيع', 'Advanced', 'متقدم', 48, 2,
  ARRAY['Master PHP & Laravel','Build scalable REST APIs','Database design & authentication'],
  ARRAY['إتقان PHP و Laravel','بناء APIs قابلة للتوسع','قواعد بيانات وأنظمة مصادقة'],
  ARRAY['PHP','Laravel','MySQL','Redis'], 5),
('sdet', 'TestTube', '🧪', 'from-yellow-500 to-red-500', 'SDET Bootcamp', 'معسكر SDET', 'Build automation test frameworks', 'بناء أُطر اختبار آلية', '10 Weeks', '10 أسابيع', 'Intermediate → Advanced', 'متوسط → متقدم', 44, 2,
  ARRAY['Build automation test frameworks','API & performance testing','CI/CD integration'],
  ARRAY['بناء أُطر اختبار آلية','اختبار API والأداء','تكامل CI/CD'],
  ARRAY['Selenium','Cypress','Postman','Jenkins'], 6),
('design', 'Palette', '🎨', 'from-pink-500 to-orange-500', 'UI/UX Design', 'تصميم UI/UX', 'User research, prototyping & design systems', 'بحث المستخدمين والنماذج الأولية وأنظمة التصميم', '10 Weeks', '10 أسابيع', 'Beginner', 'مبتدئ', 42, 4,
  ARRAY['Master Figma & design systems','User research & prototyping','Build a professional portfolio'],
  ARRAY['إتقان Figma وأنظمة التصميم','بحث المستخدم والنماذج','بناء محفظة احترافية'],
  ARRAY['Figma','FigJam','Maze','Notion'], 7),
('devops', 'Rocket', '🚀', 'from-violet-500 to-purple-600', 'DevOps & Cloud (AWS/Docker/K8s)', 'DevOps والسحابة', 'Build full CI/CD pipelines & deploy on AWS', 'بناء خطوط CI/CD كاملة والنشر على AWS', '8 Weeks', '8 أسابيع', 'Intermediate → Advanced', 'متوسط → متقدم', 40, 2,
  ARRAY['Build full CI/CD pipelines','Container orchestration with K8s','Deploy on AWS'],
  ARRAY['بناء خطوط CI/CD كاملة','إدارة الحاويات وKubernetes','نشر على AWS'],
  ARRAY['Docker','Kubernetes','AWS','GitHub Actions'], 8),
('ai-ml', 'Brain', '🧠', 'from-emerald-500 to-teal-600', 'AI & Machine Learning with Python', 'الذكاء الاصطناعي وتعلم الآلة', 'Data science & ML fundamentals to production', 'علم البيانات والتعلم الآلي من الأساسيات للإنتاج', '12 Weeks', '12 أسبوع', 'Intermediate → Advanced', 'متوسط → متقدم', 52, 3,
  ARRAY['Data science & ML fundamentals','Build & train ML models','Deploy AI models to production'],
  ARRAY['أساسيات علم البيانات والتعلم الآلي','بناء نماذج ML وتدريبها','نشر نماذج AI في الإنتاج'],
  ARRAY['Python','TensorFlow','PyTorch','Pandas'], 9),
('cybersecurity', 'Lock', '🔒', 'from-red-500 to-rose-600', 'Cybersecurity Fundamentals', 'أساسيات الأمن السيبراني', 'Ethical penetration testing & security audits', 'اختبار الاختراق الأخلاقي وتدقيق الأمان', '8 Weeks', '8 أسابيع', 'Intermediate', 'متوسط', 38, 2,
  ARRAY['Cybersecurity fundamentals','Ethical penetration testing','Security assessments & audits'],
  ARRAY['أساسيات الأمن السيبراني','اختبار الاختراق الأخلاقي','تقييمات الأمان والتدقيق'],
  ARRAY['Kali Linux','Burp Suite','Wireshark','Metasploit'], 10),
('product', 'Briefcase', '💼', 'from-indigo-500 to-purple-500', 'Product Management', 'إدارة المنتجات', 'Product strategy, Agile & stakeholder management', 'استراتيجية المنتج وAgile وإدارة أصحاب المصلحة', '6 Weeks', '6 أسابيع', 'Intermediate', 'متوسط', 34, 1,
  ARRAY['Product strategy & discovery','Agile & Scrum mastery','Stakeholder management'],
  ARRAY['استراتيجية المنتج والاكتشاف','Agile و Scrum','إدارة أصحاب المصلحة'],
  ARRAY['Jira','Notion','Miro','Amplitude'], 11),
('corporate', 'Building2', '🏢', 'from-gray-500 to-slate-600', 'Corporate Custom', 'برامج مؤسسية مخصصة', 'Programs tailored to your team', 'برامج مصممة لفريقك', 'Flexible', 'مرن', 'Custom', 'مخصص', 0, 0,
  ARRAY['Programs tailored to your team','Hands-on technical workshops','Performance assessment & follow-up'],
  ARRAY['برامج مصممة لفريقك','ورش عمل تقنية عملية','تقييم ومتابعة الأداء'],
  ARRAY[]::text[], 12);
